defmodule AIBrain.Repo.GoalSchemaTest do
  use ExUnit.Case, async: false

  alias AIBrain.Repo
  alias AIBrain.Data.Goal, as: Schema

  import Ecto.Changeset

  setup do
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(Repo)
    :ok
  end

  defp errors_on(changeset) do
    Ecto.Changeset.traverse_errors(changeset, fn {msg, opts} ->
      Enum.reduce(opts, msg, fn {key, value}, acc ->
        String.replace(acc, "%{#{key}}", to_string(value))
      end)
    end)
  end

  describe "changeset/2" do
    test "valid changeset with required fields" do
      attrs = %{
        id: "goal-1",
        title: "Launch MVP"
      }

      changeset = Schema.changeset(%Schema{}, attrs)

      assert changeset.valid?
      assert get_change(changeset, :id) == "goal-1"
      assert get_change(changeset, :title) == "Launch MVP"
    end

    test "requires title" do
      changeset = Schema.changeset(%Schema{}, %{})

      refute changeset.valid?
      errors = errors_on(changeset)

      # ID is auto-generated by SchemaHelpers.put_generated_id()
      refute errors[:id]
      assert errors[:title]
    end

    test "validates status inclusion" do
      attrs = %{
        id: "goal-1",
        title: "Test",
        status: "invalid"
      }

      changeset = Schema.changeset(%Schema{}, attrs)

      refute changeset.valid?
      assert errors_on(changeset)[:status]
    end

    test "validates priority range" do
      attrs = %{
        id: "goal-1",
        title: "Test",
        priority: 10
      }

      changeset = Schema.changeset(%Schema{}, attrs)

      refute changeset.valid?
      assert errors_on(changeset)[:priority]
    end

    test "allows parent_id reference" do
      attrs = %{
        id: "sub-goal-1",
        title: "Sub goal",
        parent_id: "goal-1"
      }

      changeset = Schema.changeset(%Schema{}, attrs)

      assert changeset.valid?
      assert get_change(changeset, :parent_id) == "goal-1"
    end
  end
end
